export const NEWS = {
  LOAD: "LOAD",
  LOAD_SUCCESS: "LOAD_SUCCESS",
  LOAD_FAIL: "LOAD_FAIL",
  RESET: "RESET",
  SET_NEWS_KEYWORD: "SET_NEWS_PARAM",
  SET_SEARCH_KEYWORD: "SET_SEARCH_KEYWORD",
  HANDLE_KEYWORD_CHANGE: "HANDLE_KEYWORD_CHANGE",
};

export const CRYPTO = {
  LOAD: "CRYPTO_LOAD",
  LOAD_SUCCESS: "CRYPTO_LOAD_SUCCESS",
  LOAD_FAIL: "CRYPTO_LOAD_FAIL",
  SET_CRYPTO_PARAM: "SET_CRYPTO_PARAM",
  RESET: "CRYPTO_RESET",
  SELECT: "SELECT_CRYPTO",
};

export const MENU = {
  DISPLAY: "DISPLAY_MENU",
};

export const NAV = {
  DISPLAY: "DISPLAY_NAV",
};
